### ISSUE TITLE
Rely on the parent element size instead of the viewport

### ISSUE THREAD

**Issue by JordyDeGroeve** [nikolasp/react-timetable-events#11]
From what I can see it is not possible to resize the dimensions of the table as a whole.
It relies on the viewport of the root. (it is responsive though 👏 )

**REQUEST:**
Would it be possible to rely on the size of the parent element (or to resize the root somehow)?
So if I put this timetable in a div with a fixed size of 800x800px, the table scales accordingly?

**Comment by nikolasp** [comment]
Hey @JordyDeGroeve. 
Sorry for the late reply! 
Check out the newest version.
https://codesandbox.io/s/n1n9knx2nm?file=/src/index.js
