### ISSUE TITLE
customize color for each events

### ISSUE THREAD

**Issue by notradhifauzan** [nikolasp/react-timetable-events#20]
Hi! may I know how to change the color for each event? I've go through the documentation and I still couldn't find a way. Thanks in advance!

**Comment by BrunoHenrique00** [comment]
Hey @notradhifauzan, you can use the prop `renderEvent` to make your own styles.

``` js
<TimeTable
        ...otherProps
        renderEvent={({ event, classNames, defaultAttributes }) => {
          return (
            <div
              {...defaultAttributes}
              title={event.name}
              key={event.id}
              style={{
                ...defaultAttributes.style,
                background: '#' + event.bgColor,
              }}
            >
             ...other HTML tags that you need
            </div>
          );
        }}
      />
```

The key here is setting the style inside the div and giving a bgColor. By default `event` does not have a `bgColor` prop so you have 2 options, put a color statically for all events or give a specific color for each events inside the `event` as I did here is in this snippet.

**Comment by notradhifauzan** [comment]
> Hey @notradhifauzan, you can use the prop `renderEvent` to make your own styles.
> 
> ```js
> <TimeTable
>         ...otherProps
>         renderEvent={({ event, classNames, defaultAttributes }) => {
>           return (
>             <div
>               {...defaultAttributes}
>               title={event.name}
>               key={event.id}
>               style={{
>                 ...defaultAttributes.style,
>                 background: '#' + event.bgColor,
>               }}
>             >
>              ...other HTML tags that you need
>             </div>
>           );
>         }}
>       />
> ```
> 
> The key here is setting the style inside the div and giving a bgColor. By default `event` does not have a `bgColor` prop so you have 2 options, put a color statically for all events or give a specific color for each events inside the `event` as I did here in this snippet.

Awesome! I appreciate this and will look into it immediately
